apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: task-planner
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    ingressClassName: nginx
    rules:
        - host: oss-knowledge-task-planner.4.230.158.187.nip.io
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: task-planner
                            port:
                                number: 8004

