apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oss-knowledge-embedding-prod
resources:
- ../../base
patches:
- path: deployment-patch.yaml

images:
- name: oss-knowledge-embedding-server
  newName: ossknowledgeregistry.azurecr.io/oss-knowledge-embedding-server
  newTag: latest

labels:
- includeSelectors: false
  pairs:
    environment: prod