apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oss-knowledge-backend-dev
resources:
- ../../base
namePrefix: dev-
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml

images:
- name: oss-knowledge-task-planner
  newName: ossknowledgeregistry.azurecr.io/oss-knowledge-task-planner
  newTag: latest

labels:
- includeSelectors: false
  pairs:
    environment: dev

