apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oss-knowledge-intent-classifier-dev

resources:
    - ../../base

patchesStrategicMerge:
    - deployment-patch.yaml
    - ingress-patch.yaml

images:
    - name: oss-knowledge-intent-classifier
      newName: ossknowledgeregistry.azurecr.io/oss-knowledge-intent-classifier
      newTag: 4-latest

namePrefix: dev-
