apiVersion: v1
kind: Secret
metadata:
  name: mem0-secrets
  namespace: oss-knowledge-mem0-dev
type: Opaque
stringData:
  AZURE_API_KEY: "7937465a33d34854a6b52fe909756d16"
  AZURE_ENDPOINT: "https://multiagent-openai-service.openai.azure.com/"
  AZURE_API_VERSION: "2024-02-15-preview"
  AZURE_DEPLOYMENT: "gpt-4.1-mini"
