apiVersion: v1
kind: Service
metadata:
  name: mem0-service
  namespace: oss-knowledge-mem0-dev
spec:
  selector:
    app: mem0-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
