apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
type: Opaque
data:
    username: b3Nz
    password: b3NzMTIzNCE=
---
apiVersion: v1
kind: Secret
metadata:
    name: api-keys
type: Opaque
data:
    embedding-api-key: OGEwNTU5ZjUwYWNmNDA3NDljNGI0NWZjOWYyMWI2OTM=
    gpt-api-key: OGEwNTU5ZjUwYWNmNDA3NDljNGI0NWZjOWYyMWI2OTM=
