apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oss-knowledge-intent-classifier

resources:
    - namespace.yaml
    - secret.yaml
    - deployment.yaml
    - service.yaml
    - ingress.yaml

images:
    - name: oss-knowledge-intent-classifier
      newName: ossknowledgeregistry.azurecr.io/oss-knowledge-intent-classifier
      newTag: latest

commonLabels:
    app: intent-classifier
    version: v1.0.0
