apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oss-knowledge-backend-prod

resources:
- ../../base

patches:
- target:
    kind: Ingress
    name: oss-knowledge-meta-api
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: oss-knowledge-meta-api.4.230.158.187.nip.io
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1enable-cors
      value: "true"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-allow-origin
      value: "http://oss-knowledge-front.4.230.158.187.nip.io"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-allow-methods
      value: "GET,POST,PUT,DELETE,OPTIONS"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-allow-headers
      value: "Authorization,Content-Type,X-Request-Id,X-Session-Id"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-expose-headers
      value: "X-Request-Id"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-allow-credentials
      value: "true"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1proxy-read-timeout
      value: "3600"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1proxy-send-timeout
      value: "3600"

commonLabels:
  app: oss-knowledge-meta-api
  environment: prod

